name: publish new classifiers
on:
  workflow_dispatch:
  schedule:
    - cron:  '1 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: install deps
          run: |
            python -m pip install trove-classifiers
            cargo install cargo-bump
        - name: build with latest trove
          run: |
            cd src/
            python build.py
            cargo fmt --all
        - name: version bump if changed
          run: |
            set -x
            if git diff --exit-code; then
              exit 1
            fi
            git config --global user.email '<>'
            git config --global user.name "$GITHUB_ACTOR"
            git commit -am "New trove classifiers"
            git status
            cargo bump minor --git-tag || git diff
            git push --follow-tags
        - name: build
          uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
        - name: publish
          uses: katyo/publish-crates@v2
          with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
